### ISSUE TITLE
C++ client infer script needed [feature]

### ISSUE THREAD

**Issue by sudapure** [isarsoft/yolov4-triton-tensorrt#1]
Most of the code in the repo, looks for building network and serializing plan file, but without client infer script it looks incomplete, it would be interesting to have infer client script as consuming triton server as shared lib, instead of calling over gRPC or HTTP.

**Comment by philipp-schmidt** [comment]
@sudapure It ain't c++ (and frankly I'm not sure I will have time to code a c++ client, but it is VERY similar code and all the post- and preprocessing c++ code can be copied from the tensorrtx repo), but check out the working python client example under clients/python

**Comment by philipp-schmidt** [comment]
If you definitely need a shared lib, [you can start from here](https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/examples/simple_grpc_infer_client.cc) and just develop the very same application in c++ and look at the python client for steps. OpenCV code is practically identical function calls and post- and preprocessing can be copied from [tensorrtx implementation](https://github.com/wang-xinyu/tensorrtx/blob/c20e2f9e84758b6facf5b0c10bd16773878d28ad/yolov4/yolov4.cpp#L44)

**Comment by sudapure** [comment]
@philipp-schmidt , thanks for the commit i will go through official tensorRT doc. for shared lib support, however will it be possible to make use of the per-processing and post-processing methods here, for yolov5 implementation in tensortRT

**Comment by philipp-schmidt** [comment]
Hi,
I don't understand the question sorry. You want to use the pre- and postprocessing for yolov5?

**Comment by sudapure** [comment]
@philipp-schmidt , yes will it be possible to use  pre- and post-processing for yolov5

**Comment by philipp-schmidt** [comment]
I don't know what the output of yolov5 is, you have to look that up. yolov4 performs as well (if not better) then yolov5.

**Comment by sudapure** [comment]
ok, thanks. i will look into it!
