### ISSUE TITLE
Client side questions

### ISSUE THREAD

**Issue by ontheway16** [isarsoft/yolov4-triton-tensorrt#14]
Hi, from documents, triton supports different versions of models, under /1/, 2, 3, etc. and newest one is considered /1/ folder.

How can we indicate which version of a model used in a specific inference request, via client.py ? I may prefer an older version sometimes. If its working this way.

**Comment by philipp-schmidt** [comment]
Hi,

yes the SDK supports passing the flag in most calls. Have a look e.g. here:
https://github.com/triton-inference-server/server/blob/92099af2a1a2915747f5647d5acd35c0799e4730/src/clients/python/library/tritonclient/grpc/__init__.py#L949
