### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by chiyukunpeng** [isarsoft/yolov4-triton-tensorrt#16]
root@ubuntu:/home/cp/project/yolov5# docker run --gpus all --rm --shm-size=1g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v$(pwd)/triton_deploy/models:/models -v$(pwd)/triton_deploy/plugins:/plugins --env LD_PRELOAD=/plugins/libmyplugins.so nvcr.io/nvidia/tritonserver:20.09-py3 tritonserver --model-repository=/models --strict-model-config=false --grpc-infer-allocation-pool-size=16 --log-verbose 1

/bin/bash: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by philipp-schmidt** [comment]
Make sure you built the engine files wit the exact same tensorrt version as the version you are using wit triton inference server.

**Comment by chiyukunpeng** [comment]
Thanks!
