### ISSUE TITLE
Config.pbtxt requirement file

### ISSUE THREAD

**Issue by chiehpower** [isarsoft/yolov4-triton-tensorrt#24]
Hi isarsoft, 

I really appreciate your contributions on this repository!!
I can successfully generate the tensorrt engine on TensorRT 20.03.1 image from NGC.
I wonder where can I get the config.pbtxt file in order to deploy on model repository of triton inference server?

Thank you so much!

BR,
Chieh

**Comment by francescooliva** [comment]
Hi, when starting the triton server  if you pass the param  `--strict-model-config=false`  you don't need the config file because Triton should generate it for you, like the one below:
```
platform: "tensorrt_plan"
max_batch_size: 1
input {
  name: "data"
  data_type: TYPE_FP32
  dims: 3
  dims: 608
  dims: 608
}
output {
  name: "prob"
  data_type: TYPE_FP32
  dims: 7001
  dims: 1
  dims: 1
}
default_model_filename: "model.plan"
```

**Comment by chiehpower** [comment]
Dear @francescooliva ,

Thanks for your reply and your important information!
I will test again.
Thank you!
