### ISSUE TITLE
how to get the “.engine” file from the model trained by myself

### ISSUE THREAD

**Issue by michaelwithu** [isarsoft/yolov4-triton-tensorrt#27]
When using the ".wts" file downloaded from Google Driver,I can get the yolov4.engine successfully.

However when change the weight file to mine, I got error while running the ./main 
The error is :
main: /yolov4-triton-tensorrt/networks/../utils/weights.h:17: std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights> loadWeights(std::__cxx11::string): Assertion `count > 0 && "Invalid weight map file."' failed.

By the way. it is error when uisng the weight downloaded from "https://github.com/AlexeyAB/darknet" which size is 246MB.

What should  i do to transform my model to ".engine"

**Comment by philipp-schmidt** [comment]
Have a closer look into the readme, there is a link to a tutorial on creating your own wts file
