### ISSUE TITLE
how to deploy yolov5 model with triton inference server

### ISSUE THREAD

**Issue by Amanda-Barbara** [isarsoft/yolov4-triton-tensorrt#30]
can you share the tutorial about https://github.com/ultralytics/yolov5 trained model with triton inference server? thanks.

**Comment by philipp-schmidt** [comment]
It's on the roadmap - but I don't think it will happen anytime soon. However, there are multiple yolov5 implementations for TensorRT which are identical in implementation to the yolov4 in this repo that you can deploy exactly like its described in the README of this repo by just replacing yolov4:
https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5

**Comment by Amanda-Barbara** [comment]
@philipp-schmidt I will try it, thanks very much.

**Comment by huynhbaobk** [comment]
I have already try yolov5 with triton https://github.com/huynhbaobk/tensorrt-triton-yolov5

**Comment by tienluongngoc** [comment]
@Amanda-Barbara you can try this https://github.com/tienluongngoc/yolov5_triton_inference_server

**Comment by danudeep90** [comment]
@tienluongngoc, @huynhbaobk  : Can you share the config.pbtxt file that you used for the model that you used. I am using this 
but facing issue in postprocess function

name: "yolov5m_torch"
platform: "pytorch_libtorch"
max_batch_size : 0
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [1, 25200 , 85]
  }
]
default_model_filename: "yolov5m.torchscript"
