### ISSUE TITLE
C++ program

### ISSUE THREAD

**Issue by YLongJin** [isarsoft/yolov4-triton-tensorrt#41]
I have read the officail document，but new I already not clearly this triton.
I want to know is it support ,in my C++ TRT program,in local GPU, deploy .eng file to infer. I just want implment the data parallelistion, like you program 
If you can help me, i will pleasure .

**Comment by philipp-schmidt** [comment]
You can have a look at how to do this in a different repo which comes with c++ code for this:

https://github.com/wang-xinyu/tensorrtx/tree/master/yolov4

**Comment by olibartfast** [comment]
Hi if you're interested I tried to implement on my repo [here](https://github.com/olibartfast/yolov4-triton-cpp-client)  a basic triton  c++ client example with inference code from wang-xinyu repo and the .plan model generated with this repo code

**Comment by philipp-schmidt** [comment]
Hi @olibartfast 
I never got the time to implement the c++ client even though Triton has very good documentation and examples. Would you mind PR'ing your code into this repo? There is room under the folder `clients/c++`. I will of course add you to a list of contributors in the README.md if you want. Would be very much appreciated. Cheers.

**Comment by philipp-schmidt** [comment]
C++ client example now available for v1.3.0 under clients/c++
