### ISSUE TITLE
How to deploy multiple customized yolov4 models on the triton server

### ISSUE THREAD

**Issue by Amanda-Barbara** [isarsoft/yolov4-triton-tensorrt#42]
@philipp-schmidt I can deploy a customized yolov4 model with plugin on the triton sever , Now I want to deploy multiple customized yolov4 models with different CLASS_NUM on the triton server, How should I do it ? Thanks .

**Comment by philipp-schmidt** [comment]
I believe you should be just able to do that. You compile your code for the first engine and create the engine, then you change the class_num, compile again and build your second engine.

The plugin has been changed recently to be able to support multiple models even if they differ in their settings. You no longer need multiple yolo layer plugins if the parameters change.

**Comment by Amanda-Barbara** [comment]
@philipp-schmidt yes, I have seen your new version, you have done it, Thanks!
