### ISSUE TITLE
yolov4-tiny model accuracy not right

### ISSUE THREAD

**Issue by Amanda-Barbara** [isarsoft/yolov4-triton-tensorrt#49]
@philipp-schmidt 
I have trained custom yolov4-tiny model and deployed to the triton server, but the accuracy of yolov4-tiny model is not correct, How shuold I debug step by step ? thanks .

**Comment by philipp-schmidt** [comment]
It's hard to do that. You can follow this discussion:
https://github.com/jkjung-avt/tensorrt_demos/issues/315

**Comment by philipp-schmidt** [comment]
Polygraphy seems to be a good tool to do that
