### ISSUE TITLE
where is test time?

### ISSUE THREAD

**Issue by wxr521314** [isarsoft/yolov4-triton-tensorrt#61]
Hi:
 I would like to ask, what is the time of 200ms and 3.00185s？

![image](https://user-images.githubusercontent.com/53425125/147537288-8effe619-b7a8-4d3a-8e63-9cbdadd21ef0.png)

My results are as follows: which is the inference time of the test?

![image](https://user-images.githubusercontent.com/53425125/147537637-ab58f56c-be08-44d8-ac6d-8d3078aa27c5.png)

**Comment by philipp-schmidt** [comment]
The times that you highlighted are not very important.
The values under "performance summary" matter. You get a throughput of 2.8 inferences per second.
For all the other metrics you can call the verbose logs for explanations, exactly as the screenshot says ;)
