### ISSUE TITLE
Can I use this repo to use custom trained yolo-v4 with single class 

### ISSUE THREAD

**Issue by varunvv** [isarsoft/yolov4-triton-tensorrt#62]
I am getting error while converting yolo-v4 model trained for detecting single class objects. What  modification  should I make  in order to use a custom trained yolo-v4 model.

**Comment by philipp-schmidt** [comment]
Generally you need to change all settings in the following lines to your model:

https://github.com/isarsoft/yolov4-triton-tensorrt/blob/543fde846b2751d6ab394339e005e2754de22972/networks/yolov4.h#L14-L31
