### ISSUE TITLE
./main: error while loading shared libraries

### ISSUE THREAD

**Issue by ontheway16** [isarsoft/yolov4-triton-tensorrt#8]
I am on the path of training of custom data, I have successfully generated yolov4.wts from custom .weights file, run ```./main```, generated the .engine and tested the client.py without problems. This was for 100th epoch (normally, no objects detected), so after training reach to 1000th, followed the whole path to regenerate .engine for 1000th epoch weights.

But now, when I run ```./main```
its now reporting an error;
```
(yolov4-triton) qgs@qgs-MS-7A74:~/yolov4-triton-tensorrt/build$ ./main
./main: error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory
```
This has happened before and I have deleted local repo and re-cloned your repo, started from scratch (make etc) to make it function. What I am doing wrong here ? ( I am not running the ```./main``` from inside docker).
This is whats available in the folder:
```
drwxr-xr-x 3 root root      4096 Eyl 23 19:48 .
drwxr-xr-x 9 qgs  qgs       4096 Eyl 23 19:50 ..
-rw-r--r-- 1 root root     21592 Eyl 23 19:32 CMakeCache.txt
drwxr-xr-x 7 root root      4096 Eyl 23 19:32 CMakeFiles
-rw-r--r-- 1 root root      1498 Eyl 23 19:32 cmake_install.cmake
-rwxr-xr-x 1 root root    884880 Eyl 23 19:32 liblayerplugin.so
-rwxr-xr-x 1 root root    125240 Eyl 23 19:32 main
-rw-r--r-- 1 root root      5159 Eyl 23 19:32 Makefile
-rw-r--r-- 1 root root 424181144 Eyl 23 19:48 yolov4.engine
-rw-r--r-- 1 root root 579892906 Eyl 23 20:48 yolov4.wts

**Comment by philipp-schmidt** [comment]
> I am not running the ./main from inside docker

you can't run a binary linked against shared libs from your container on your host if those libraries are not installed on your host. Install all dependencies or run inside docker.
